### ISSUE TITLE
RDF loader breaks on XML SPDX produced by the maven plugin

### ISSUE THREAD

**Issue by jdolitsky** [spdx/tools-golang#149] opened 2022-06-08 20:24 UTC
Generated an XML SPDX doc using the maven plugin (https://github.com/spdx/spdx-maven-plugin) with:

```
mvn spdx:createSPDX
```

The top-level project had no license itself, resulting in a document that looks like this:
```
...
  <spdx:SpdxDocument rdf:about="http://spdx.org/spdxpackages/myproject-1.0-SNAPSHOT#SPDXRef-DOCUMENT">
    <spdx:relationship>
      <spdx:Relationship>
        <spdx:relationshipType rdf:resource="http://spdx.org/rdf/terms#relationshipType_describes"/>
        <spdx:relatedSpdxElement>
          <spdx:Package rdf:about="http://spdx.org/spdxpackages/myproject-1.0-SNAPSHOT#SPDXRef-1">
            <spdx:relationship>
              <spdx:Relationship>
                <spdx:relationshipType rdf:resource="http://spdx.org/rdf/terms#relationshipType_other"/>
                <spdx:relatedSpdxElement>
                  <spdx:Package rdf:about="http://spdx.org/spdxpackages/myproject-1.0-SNAPSHOT#SPDXRef-4">
                    <spdx:versionInfo>4.0.1</spdx:versionInfo>
                    <spdx:copyrightText>UNSPECIFIED</spdx:copyrightText>
                    <spdx:licenseInfoFromFiles>
                      <spdx:noassertion rdf:about="http://spdx.org/rdf/terms#noassertion"/>
                    </spdx:licenseInfoFromFiles>
                    ...
```

When running
```
doc, err := rdfloader.Load2_2(file)
```

I receive error:

```
error parsing given spdx document: error setting a package inside a relationship: error setting a package inside a relationship: Unknown subTag (http://spdx.org/rdf/terms#noassertion) found while parsing AnyLicense
```

If I manually remove this part from the XML document:
```
<spdx:noassertion rdf:about="http://spdx.org/rdf/terms#noassertion"/>
```

Then things work properly.

I'm not sure if the issue is in the maven plugin or here, but the document appears to at least be at least valid XML.

**Comment by jdolitsky** [comment] 2022-06-08 20:28
Related to https://github.com/spdx/spdx-maven-plugin/issues/46

**Comment by RishabhBhatnagar** [comment] 2022-06-12 08:15
Can you attach the file used?

I tried running rdfloader by completing the given snippet.
Couldn't replicate the issue.

```
<rdf:RDF
        xmlns:spdx="http://spdx.org/rdf/terms#"
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>
    <spdx:SpdxDocument rdf:about="http://spdx.org/spdxpackages/myproject-1.0-SNAPSHOT#SPDXRef-DOCUMENT">
        <spdx:relationship>
            <spdx:Relationship>
                <spdx:relationshipType rdf:resource="http://spdx.org/rdf/terms#relationshipType_describes"/>
                <spdx:relatedSpdxElement>
                    <spdx:Package rdf:about="http://spdx.org/spdxpackages/myproject-1.0-SNAPSHOT#SPDXRef-1">
                        <spdx:relationship>
                            <spdx:Relationship>
                                <spdx:relationshipType rdf:resource="http://spdx.org/rdf/terms#relationshipType_other"/>
                                <spdx:relatedSpdxElement>
                                    <spdx:Package
                                            rdf:about="http://spdx.org/spdxpackages/myproject-1.0-SNAPSHOT#SPDXRef-4">
                                        <spdx:versionInfo>4.0.1</spdx:versionInfo>
                                        <spdx:copyrightText>UNSPECIFIED</spdx:copyrightText>
                                        <spdx:licenseInfoFromFiles>
                                            <spdx:noassertion rdf:about="http://spdx.org/rdf/terms#noassertion"/>
                                        </spdx:licenseInfoFromFiles>
                                    </spdx:Package>
                                </spdx:relatedSpdxElement>
                            </spdx:Relationship>
                        </spdx:relationship>
                    </spdx:Package>
                </spdx:relatedSpdxElement>
            </spdx:Relationship>
        </spdx:relationship>
    </spdx:SpdxDocument>
</rdf:RDF>
```

**Comment by RishabhBhatnagar** [comment] 2023-01-19 06:13
Closing the issue as we were not able to reproduce it. Feel free to re-open this issue once we have the file that throws this error.

**Closed by RishabhBhatnagar** 2023-01-19 06:13 UTC
